# Site settings
title: KT Codes
header-img: img/home-bg.png
email: katiecannell@gmail.com
copyright_name: ktcannell
description: > # this means to ignore newlines until "baseurl:"
  Work, Yoga, Code, Sleep, Repeat
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ktcannell
learn_profile: ktcannell
email_username: katiecannell@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
